services:
  sign_node:
    image: sign-node:latest
    build:
      context: .
      target: prod
    command: "python3 almalinux_sign_node.py -v"
    restart: on-failure
    volumes:
      - "./node-config:/root/.config"
      - "./almalinux_sign_node.py:/sign-node/almalinux_sign_node.py"
      - "./sign_node:/sign-node/sign_node"
