services:
  sign_node:
    image: sign-node:latest
    build:
      context: .
    command: "python3 almalinux_sign_node.py -v"
    volumes:
      - ".:/sign-node"
      - "./node-config/sign_node.yml:/root/.config/sign_node.yml"
