services:
  sign_node:
    image: sign-node:latest
    build:
      context: .
    command: "python3 almalinux_sign_node.py -v"
    volumes:
      - "./node-config:/root/.config"
      - ".:/sign-node"
